### ISSUE TITLE
Persistent Volume Design

### ISSUE THREAD

**Issue by PotatoParser** [digi-project/digi#24]
**Is your feature request related to a problem? Please describe.**

Currently, there is no persistence for digivices and the lake; data from runtime does not persist through restarts.

Design a persistence volume that adheres to the following:
1. Persistence is optional; not enabled by default
2. Can be enabled at profile level for a kind OR at instance level (`digi run ...`)
3. Persistence should be attachable with any storage device; Dropbox, Box, Google Drive, locally, etc.

Persistence Needed For The Following:
- [ ] [Lake](#22 )
- [ ] [Matter](#25 )

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by silveryfu** [comment]
Don't we need persistence volume for #25 too? 

This one perhaps should be made PR soon. Outlining a few key points:
- Naming of the PV should be the digi's name.
- Digi run should dynamically generate the PV definition.
- Digi stop removes the PV by name.
- CLI should have a flag/param on whether to provision a PV (e.g. `-p` in digi run)
- Some meta digi who always need a PV should have the `digi space start` commands use the above flag by default
- Otherwise the PV is default off

**Comment by PotatoParser** [comment]
What should the limitations of dynamically created PV's be? My thoughts are:
- Size: Size of PV
- Path: Mounting point of PV
- Type: Hard Disk, Azure, etc.

Perhaps something like: `digi run lamp l1 --volume "250G, /mnt, Azure"`
or `digi run lamp l1 --volume:size 250G --volume:mount /mnt --volume:type Azure`

**Comment by silveryfu** [comment]
@PotatoParser The interface you propose above makes sense! Any thoughts on the default configuration? Local filesystem?

**Comment by PotatoParser** [comment]
We should probably use Helm's Golang library for templating. Local filesystem should work for a good default value!

**Comment by PotatoParser** [comment]
Due to limitations in `gen.py`, I'm revising the PV to only support one PV:
```yaml
persistent_volume:
  size: 10Mi
  type: local
  path: /mnt
```
