### ISSUE TITLE
Unable to access lake service when deployed on Minikube

### ISSUE THREAD

**Issue by silveryfu** [digi-project/digi#30]
**Describe the bug**

Running dSpace on Minikube (v1.28.0) shows the following error:

> OS signals are ignored: running not in the main thread. 
Traceback (most recent call last): 
File "handler.py", line 83, in digi.run() File "/src/driver/digi/main.py", line 104, in run 
    digi.pool.create_branch_if_not_exist("model") 
File "/src/driver/digi/data/pool.py", line 102, in create_branch_if_not_exist 
    if not self.client.branch_exist(self.name, branch): 
File "/src/driver/digi/data/zed.py", line 34, in branch_exist 
    records = self.query(f" from {pool): branches") 
File "/src/driver/digi/data/zed.py", line 38, in query return 
    zjson.decode_raw(self.query_raw(query)) 
File "/src/zed-cli/zed.py", line 63, in query_raw 
    self._raise_for_status(r) 
File "/src/zed-cli/zed.py", line 74, in _raise_for_status 
    raise RequestError(error, response) zed.RequestError: 11: pool not found

`digi space connect` to `lake` or the app digi `l1` shows that the lake cannot be accessed via the ClusterIP `http://lake:6534`.

**To Reproduce**
1. `digi space start` or `digi space start lake`
2. `digi run lamp l1`
 
**Additional context**

**Comment by PotatoParser** [comment]
Does this affect version 1.27?

**Comment by silveryfu** [comment]
@PotatoParser I'm not sure - we should perhaps figure it out

**Comment by silveryfu** [comment]
Is this really a bug on our end? Removing the two tags for now until we understand the issue better. It seems a Minikube-on-Docker issue not a Digi issue.

**Comment by NauqGnesh** [comment]
> Is this really a bug on our end? Removing the two tags for now until we understand the issue better. It seems a Minikube-on-Docker issue not a Digi issue.

It's not an issue with Digi. It's working with Docker Desktop's Kubernetes and Kind on my end. 

For folks that really want to use minikube, you'll have to create a tunnel to the lake as the Node IP isn't reachable directly when running minikube + Docker as detailed [here](https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-service-with-tunnel). I haven't tested it and am unsure why minikube isn't compatible with Docker Desktop. I'll make a detailed writeup and include the fix for minikube users once I get the bandwidth.

**Comment by vakumar1** [comment]
I was able to use the lake service after running the following in the minikube VM (`minikube ssh)`:

`sudo ip link set docker0 promisc on`

I think it makes the lake service discoverable from the lake pod itself.
